services:
  mysql:
    image: ${CORDYS_IMAGE_PREFIX}/${CORDYS_IMAGE_NAME}:${CORDYS_IMAGE_TAG}
    container_name: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${CORDYS_MYSQL_PASSWORD}"]
      interval: 6s
      timeout: 5s
      retries: 50
    entrypoint: [ "/shells/start-mysql.sh" ]
    environment:
      MYSQL_DATABASE: ${CORDYS_MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${CORDYS_MYSQL_PASSWORD}
      TZ: "Asia/Shanghai"
    ports:
      - ${CORDYS_MYSQL_PORT}:3306
    volumes:
      - ${CORDYS_BASE}/cordys/conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - cordys-mysql-data:/opt/cordys/data/mysql
    networks:
      - cordys-network
    restart: always
  cordys:
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  cordys-mysql-data:
    driver_opts:
      type: none
      device: ${CORDYS_BASE}/cordys/data/mysql
      o: bind