version: "3"
services:
  redis:
    image: ${CORDYS_IMAGE_PREFIX}/${CORDYS_IMAGE_NAME}:${CORDYS_IMAGE_TAG}
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 6s
      timeout: 5s
      retries: 50
    entrypoint: [ "/shells/start-redis.sh" ]
    environment:
      TZ: "Asia/Shanghai"
    command: [ "redis-server", "--requirepass", "${CORDYS_REDIS_PASSWORD}" ]
    ports:
      - ${CORDYS_REDIS_PORT}:6379
    volumes:
      - ${CORDYS_BASE}/cordys/conf/redis/redis.conf:/opt/cordys/conf/redis/redis.conf
      - cordys-redis-data:/data
    networks:
      - cordys-network
    restart: always
  cordys:
    depends_on:
      redis:
        condition: service_healthy

volumes:
  cordys-redis-data:
    driver_opts:
      type: none
      device: ${CORDYS_BASE}/cordys/data/redis
      o: bind